# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_controller.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import grpc_controller_pb2


class GRPCControllerBase(abc.ABC):

    @abc.abstractmethod
    async def Shutdown(self, stream: 'grpclib.server.Stream[grpc_controller_pb2.Empty, grpc_controller_pb2.Empty]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/plugin.GRPCController/Shutdown': grpclib.const.Handler(
                self.Shutdown,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc_controller_pb2.Empty,
                grpc_controller_pb2.Empty,
            ),
        }


class GRPCControllerStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Shutdown = grpclib.client.UnaryUnaryMethod(
            channel,
            '/plugin.GRPCController/Shutdown',
            grpc_controller_pb2.Empty,
            grpc_controller_pb2.Empty,
        )
