# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_broker.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import grpc_broker_pb2


class GRPCBrokerBase(abc.ABC):

    @abc.abstractmethod
    async def StartStream(self, stream: 'grpclib.server.Stream[grpc_broker_pb2.ConnInfo, grpc_broker_pb2.ConnInfo]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/plugin.GRPCBroker/StartStream': grpclib.const.Handler(
                self.StartStream,
                grpclib.const.Cardinality.STREAM_STREAM,
                grpc_broker_pb2.ConnInfo,
                grpc_broker_pb2.ConnInfo,
            ),
        }


class GRPCBrokerStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.StartStream = grpclib.client.StreamStreamMethod(
            channel,
            '/plugin.GRPCBroker/StartStream',
            grpc_broker_pb2.ConnInfo,
            grpc_broker_pb2.ConnInfo,
        )
